"use client"
// import type { Metadata } from "next";
import "./globals.css";
import { useEffect } from "react";

import Aos from "aos";
import "aos/dist/aos.css";

// export const metadata: Metadata = {
//   title: "Arief Dan Mia",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    Aos.init()
    window.scrollTo(0, 0);
  }, []);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
